По уроку 3:
1*. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.
2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.
3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).
4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).
5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.
6. Могла ли модель переобучиться? Почему?
7*. Создайте функции eval_model_l1 и eval_model_l2 с применением L1 и L2 регуляризаций соответственно.

In [6]:
import numpy as np
import matplotlib.pyplot as plt
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2,  1, 3, 3, 1, 2]], dtype = np.float64)
y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res
X_st = X.copy()
X_st[2, :] = calc_std_feat(X[2, :])
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

1*. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

Добавим маленькое число в скобки? например, 1e-100, так нулей не будет, и на результат не повлияет:

In [1]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred + 1e-100) + (1.0 - y) * np.log(1.0 - y_pred + 1e-100))
    err = np.sum(err)
    return err

2 Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [38]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [43]:
W = eval_model(X_st, y, iterations=100000, alpha=1e-2)

10000 [-2.51838389 -0.94526222  0.40028955  3.13247255] 0.3753579132752236
20000 [-4.27621379 -0.98162746 -0.27399347  4.26180494] 0.3266487190104309
30000 [-5.5601776  -1.03173743 -0.73813215  5.15120103] 0.2999315037692002
40000 [-6.58495724 -1.08568898 -1.0907878   5.89792906] 0.2825328605428863
50000 [-7.45444584 -1.13931761 -1.38008389  6.55223233] 0.26980645713504225
60000 [-8.22275796 -1.19149332 -1.62964558  7.14285198] 0.2597559180746457
70000 [-8.92045538 -1.24198217 -1.85226308  7.6870807 ] 0.2514003233342506
80000 [-9.56602232 -1.2908158  -2.05544542  8.19586001] 0.24420467569970014
90000 [-10.1712849   -1.33809799  -2.24389333   8.67643496] 0.23785244009370934
100000 [-10.74417094  -1.38394305  -2.42070613   9.13379901] 0.23214376711914236


Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [44]:
W

array([-10.74417094,  -1.38394305,  -2.42070613,   9.13379901])

In [45]:
def calc_pred_proba(W, X):
    y_pred_proba = sigmoid(np.dot(W,X))
    return y_pred_proba

In [47]:
calc_pred_proba(W, X_st)

array([0.34909577, 0.16500392, 0.99720963, 0.00128205, 0.73111739,
       0.3237184 , 0.99918914, 0.09118778, 0.40771831, 0.99034651])

Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [49]:
def calc_pred(W, X, t):
    y_pred_bool = sigmoid(np.dot(W,X)) > t
    y_pred = y_pred_bool.astype(int)
    return y_pred

In [50]:
calc_pred(W, X_st, 0.5)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [52]:
y

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [ ]:
TP
FP
TN
FN

In [ ]:
for i in range(len(y))